//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaderaConsola
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenSale
    {
        public string SHSHNM { get; set; }
        public string SHSHCI { get; set; }
        public string SOLDST { get; set; }
        public string SOLDTO { get; set; }
        public string CCLASS { get; set; }
        public string Order { get; set; }
        public Nullable<double> SLRLNO { get; set; }
        public Nullable<double> Line { get; set; }
        public string SHSPPO { get; set; }
        public string SHUDL1 { get; set; }
        public string SLPTNO { get; set; }
        public string Dept { get; set; }
        public string SLCPOL { get; set; }
        public string SHCSPO { get; set; }
        public string SLCSPT { get; set; }
        public Nullable<double> BALANCE { get; set; }
        public Nullable<double> TOTRESV { get; set; }
        public string SectW { get; set; }
        public string SectH { get; set; }
        public Nullable<double> TotalSect { get; set; }
        public string Width { get; set; }
        public string Height { get; set; }
        public string FINISH { get; set; }
        public string FINISHTYP { get; set; }
        public string FRMTYP { get; set; }
        public string SLINET { get; set; }
        public string UNITD { get; set; }
        public string DRAINT { get; set; }
        public string ORDERDATE { get; set; }
        public string PROMISEDT { get; set; }
        public Nullable<double> SLUNPR { get; set; }
        public Nullable<double> SLEXPR { get; set; }
        public string EXPRESS { get; set; }
        public Nullable<double> ADFWSDD { get; set; }
        public Nullable<double> MODATE { get; set; }
        public string MOPAST { get; set; }
        public string HOLD { get; set; }
        public string PMPDCL { get; set; }
        public string PMPSCL { get; set; }
        public string ADSCHC { get; set; }
        public int Id { get; set; }
    }
}
