//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaderaConsola.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenSalesOrder
    {
        public string Depto { get; set; }
        public string Orden { get; set; }
        public Nullable<double> Line { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> SectW { get; set; }
        public Nullable<double> SectH { get; set; }
        public Nullable<double> TotalSec { get; set; }
        public Nullable<double> Balance { get; set; }
        public int Id { get; set; }
    }
}
