//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaderaConsola.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class WoodInOrder
    {
        public int Id { get; set; }
        public string Orden { get; set; }
        public Nullable<int> Table96 { get; set; }
        public Nullable<int> Bar144 { get; set; }
        public Nullable<int> Bar120 { get; set; }
        public Nullable<int> Bar96 { get; set; }
        public Nullable<int> Crates { get; set; }
        public Nullable<int> Pallet48x48 { get; set; }
        public Nullable<int> Pallet40x48 { get; set; }
        public Nullable<int> Pallet32X32 { get; set; }
        public Nullable<int> Pallet34X56 { get; set; }
        public string RegistrationDate { get; set; }
        public string AssignmentDate { get; set; }
    }
}
